# Generated by Django 5.1.7 on 2025-04-10 08:24

import college.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_course', models.CharField(blank=True, max_length=255, null=True, verbose_name='Applied Course')),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20, verbose_name='Application Status')),
                ('submitted_documents', models.BooleanField(default=False, verbose_name='Documents Submitted')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_paid', models.BooleanField(default=False, verbose_name='Fees Paid')),
                ('documents_completed', models.BooleanField(default=False, verbose_name='Documents Completed')),
                ('admission_approved', models.BooleanField(default=False, verbose_name='Admission Approved')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='college.applicant', verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Admission Status',
                'verbose_name_plural': 'Admission Statuses',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('PAN Card', 'PAN Card'), ('10th Marksheet', '10th Marksheet'), ('12th Marksheet', '12th Marksheet'), ('Degree Certificate', 'Degree Certificate')], max_length=100)),
                ('document', models.FileField(upload_to=college.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='college.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Payment ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Amount')),
                ('currency', models.CharField(default='INR', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('ON', 'Online'), ('CA', 'Cash'), ('CD', 'Card'), ('UP', 'UPI'), ('BT', 'Bank Transfer'), ('WL', 'Digital Wallet')], max_length=2, verbose_name='Payment Method')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Transaction ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('CO', 'Completed'), ('FA', 'Failed'), ('RE', 'Refunded'), ('PR', 'Partially Refunded'), ('CA', 'Cancelled')], default='PE', max_length=2, verbose_name='Status')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payment Date')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Processed Date')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Receipt')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Invoice Number')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='college.applicant', verbose_name='Applicant')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['status', 'payment_date'], name='college_pay_status_eaf3df_idx'), models.Index(fields=['applicant', 'payment_date'], name='college_pay_applica_c71819_idx')],
            },
        ),
    ]
