# Generated by Django 5.1.7 on 2025-03-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='document',
            field=models.FileField(upload_to='media/uploads/'),
        ),
    ]
